[target.aarch64-unknown-linux-musl]
linker = "aarch64-alpine-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
[target.arm-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=-crt-static"]
